### ISSUE TITLE
Make `set_boot_partitions()` generic

### ISSUE THREAD

**Issue by kcxt** [ai-b-z/sdm845-abootctl#3]
Support other partitions, don't require that both boot partitions be written.

It would probably also be worth moving the `write_inplace` / flush out of the function so flushing can be handled by the caller.

Also, there is a bug, the partitition map keys are the partition number, not the name https://github.com/ai-b-z/sdm845-abootctl/blob/master/src/partitions.rs#L76

https://docs.rs/gpt/2.0.0/gpt/struct.GptDisk.html#method.partitions

**Comment by nia-e** [comment]
Done, thanks to the anonymous rewriter
